Traceback (most recent call last):
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%matplotlib inline
import matplotlib.pyplot as plt
import gym

env = gym.make(
    "FrozenLake-v1",
    desc=["SFFF", "FHFH", "FFFH", "HFFG"],
    map_name="4x4",
    is_slippery=False,
)

env.reset()
plt.imshow(env.render('rgb_array'))

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 13>[0;34m()[0m
[1;32m      5[0m env [38;5;241m=[39m gym[38;5;241m.[39mmake(
[1;32m      6[0m     [38;5;124m"[39m[38;5;124mFrozenLake-v1[39m[38;5;124m"[39m,
[1;32m      7[0m     desc[38;5;241m=[39m[[38;5;124m"[39m[38;5;124mSFFF[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mFHFH[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mFFFH[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mHFFG[39m[38;5;124m"[39m],
[1;32m      8[0m     map_name[38;5;241m=[39m[38;5;124m"[39m[38;5;124m4x4[39m[38;5;124m"[39m,
[1;32m      9[0m     is_slippery[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m     10[0m )
[1;32m     12[0m env[38;5;241m.[39mreset()
[0;32m---> 13[0m plt[38;5;241m.[39mimshow([43menv[49m[38;5;241;43m.[39;49m[43mrender[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mrgb_array[39;49m[38;5;124;43m'[39;49m[43m)[49m)

[0;31mTypeError[0m: render() takes 1 positional argument but 2 were given
TypeError: render() takes 1 positional argument but 2 were given

