Traceback (most recent call last):
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/hisaki/workspace/ono-lab/rl-semi/.venv/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
価値関数または行動価値関数に関して，その定義を確認し，強化学習アルゴリズムにおけるそれらの利用方法を確認します．

## 定義

まずは，一般的に用いられる価値関数/行動価値関数の定義を確認します．

- 価値関数(Value Function)
  $V(s) = \underE{}{}$
------------------

[0;36m  Input [0;32mIn [1][0;36m[0m
[0;31m    価値関数または行動価値関数に関して，その定義を確認し，強化学習アルゴリズムにおけるそれらの利用方法を確認します．[0m
[0m                                                           ^[0m
[0;31mSyntaxError[0m[0;31m:[0m invalid character in identifier

SyntaxError: invalid character in identifier (1631767636.py, line 1)

